version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pg_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fireworks_db
      POSTGRES_USER: fireworks
      POSTGRES_PASSWORD: "FSJ!801jfsd?asmoi"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

volumes:
  pg_data: